### ISSUE TITLE
error loop after pixie timeout

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#1]
NUM ESSID                 CH  ENCR  POWER  WPS?  CLIENT

---

```
1  \x00\x00\x00\x0000   6  WPA2  63db   wps 
2  b0c554a10000           1  WPA2  54db   wps   client
3  We hear you wa0000   6  WPA2  53db   wps 
4  DG1670000            11  WPA2  52db   wps 
5  DVW3200000            1  WPA2  51db   wps 
6  Wiley0000            10  WPA2  50db   wps 
7  Tuppy Glo0000          6  WPA2  50db   Locked 
8  133 K0000               6  WPA2  49db   wps 
9  TG1670000             11  WPA2  48db   wps 
```

   10  atlantis2010000     10  WPA2  46db   wps 
   11  ZOOM                   6  WPA2  45db   wps 
   12  DVW3200000             1  WPA2  44db   wps 
   13  906EBBB60000           1  WPA2  44db   wps 
   14  \x00\x00\0000        6  WPA2  44db   wps 
   15  TommyAn0000            6  WPA2  44db   wps 
   16  133 K0000               6  WPA2  44db   Locked 
   17  DG1670000             11  WPA2  43db   wps 
   18  DG1670000              1  WPA2  43db   Locked 
   19  Pand0000              11  WPA2  42db   wps 
   20  ShinySp0000            1  WPA2  42db   wps 
   21  Kirin0000              1  WPA2  42db   wps 
   22  Ony0000               1  WPA2  41db   wps 
   23  TG1670000              1  WPA2  40db   wps 
   24  DG1670000              1  WPA2  38db   Locked 
   25  McP0000               6  WPA2  38db   wps 
   26  PS0000                  1  WPA2  38db   wps 
   27  DDW360000              3  WPA   37db   wps 
   28  TG1670000             6  WPA2  37db   wps 
   29  NETGE0000             11  WPA2  37db   wps 
   30  linda'0000           11  WPA2  37db   wps 

 [+] select target numbers (1-30) separated by commas, or 'all': all

 [+] 30 targets selected.

 [0:00:00] initializing PixieWPS attack on \x00\x00\x00\x000000 (0000:79:0F)

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x0000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x0000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\0000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

 [!] unable to complete successful try in 90 seconds
 [+] skipping pixiewps on \x00\x00\x00\x00000

**Comment by aanarchyy** [comment]
Should be fixed in latest commit, please confirm,

**Comment by nuroo** [comment]
Seems fixed. No error loop after pixie timout. After pin found, hand off to reaver for passphrase happened, correctly. Test below was only natural script end. Still must test for pressing crtl C. and move on to next target

   NUM ESSID                 CH  ENCR  POWER  WPS?  CLIENT

---

```
1  mara0000                1  WPA2  25db   wps   client
2  f8e9000000           1  WPA2  20db   wps 
3  ME000000000              6  WPA2  20db   wps 
4  airp0000                6  WPA2  19db   wps 
5  DG0000000              1  WPA2  18db   wps 
6  LUZ DE0000000      6  WPA2  15db   wps 
7  TP-LIN0000000         3  WPA2  14db   wps 
8  Paulose000000        6  WPA2  13db   wps 
```

 [+] select target numbers (1-8) separated by commas, or 'all': 5

 [+] 1 target selected.

 [0:00:00] initializing PixieWPS attack on 00000000 (0000000:C4:60)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] PIN found:     00882880
 [+] Handing pin to reaver

 [0:00:00] initializing WPS PIN attack on 00000000 (0000000:C4:60)
 [0:00:07] WPS attack, 0/0 success/ttl, 

 [+] PIN found:     00882880
 [+] WPA key found: 000670A60000

 [+] 1 attack completed:

 [+] 1/1 WPA attacks succeeded
        found DG16700000 WPA key: "DG1670A600000", WPS PIN: 00882880

 [+] quitting
