### ISSUE TITLE
-paddto didnt add more time

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#11]
./wifite -ponly -pto 75 -paddto 60
  .;'                     `;,    
 .;'  ,;'`;,  `;,   WiFite v2 (r104)
.;'  ,;'  ,;'`;,  `;,`;,  
::   ::   :   ( )   :   ::   ::  automated wireless auditor
':.  ':.  ':. /_\ ,:'  ,:'  ,:'  
 ':.  ':.    /___\    ,:'  ,:'   designed for Linux
  ':.       /_____\      ,:'  
           /       \             

modified by aanarchyy(aanarchyy@gmail.com)
Credits to wiire,DataHead,soxrok2212,nxxxu,nuroo

 [+] Pixiewps attack only enabled
 [+] pixie attack timeout set to 75 seconds
 [+] Seconds to add on hash retrevial 60 seconds
............................................
 [0:00:00] initializing PixieWPS attack on air0000 (0000000:24:65)
 [+] E-Nonce found for hashes 
 [+] PKE hash foundfor hashes 
 [+] PKR hash foundfor hashes 
 [+] Authkey found for hashes 
 [0:01:16] Waiting for hashes 
 [!] unable to complete in 75 seconds
 [+] skipping pixiewps on ai0000

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on Hi000000 (0000000:70:2E)
 [+] E-Nonce found for hashes 
 [+] PKE hash foundfor hashes 
 [+] PKR hash foundfor hashes 
 [+] Authkey found for hashes 
 [0:01:16] Waiting for hashes 
 [!] unable to complete in 75 seconds
 [+] skipping pixiewps on HiB000000

Script did wait for -pto, but didnt add extra time -paddto 60 secs.

i like the confirmations given thats these options are given.

**Comment by aanarchyy** [comment]
crap, didn't get the chance to test this before commiting, ill check this now.

**Comment by aanarchyy** [comment]
Should be fixed in most recent release r106, please confirm.

**Comment by nuroo** [comment]
fixed in r106. 
./wifite -mac -ponly -pto 35 -paddto 60
 [0:00:00] initializing PixieWPS attack on rocky-road-is-the-best (0000000:5D:60)
 [+] E-Nonce found for hashes 
 [+] PKE hash foundfor hashes 
 [+] PKR hash foundfor hashes 
 [+] Authkey found for hashes 
 [0:04:36] Waiting for hashes 
 [!] unable to complete in 275 seconds
 [+] skipping pixiewps on rocky-road-is-the0000
