### ISSUE TITLE
how mac spoofing is displayed to user

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#12]
In r104 only:
mac address anonymizing enabled

I liked the spoofed mac being displayed like previous versions. Why change? Your choice of course.

**Comment by aanarchyy** [comment]
It shouldnt anonymize unless you tell it to.
what is the comand line input you are specifying?
what is the behaviour that is unexpected?
what is the expected behavior?

**Comment by nuroo** [comment]
it did random mac....

Im saying I liked how you gave more info in previous versions.  In previous versions u displayed the random mac

**Comment by nuroo** [comment]
I mean to say this not a error. Just a personal preference. I like how u had it b4. But it's your code of course

**Comment by aanarchyy** [comment]
Will look into it, the mac anonymizing portion is more original code that i did not write. 
I looked at the code and i can see what they did wrong, i will fix it in the next revision, most likely tonight.  with more additional features/bug fixes( formatting, fixed paddto).  just finishing up the endless loop part, it works, just looking for more output on exit.

**Comment by aanarchyy** [comment]
Should be fixed in most recent release r106, please confirm.

**Comment by nuroo** [comment]
fixed in r106.

**Comment by nuroo** [comment]
[+] changing mon0's MAC from 00000000000-00-00-00-00-00-00-00-00-00-00 to 0000000d:b6:f5... done
 [+] changing mon0's MAC from 00000000000-00-00-00-00-00-00-00-00-00-00 to 00000005:c2:b6... done

think just need to fix wording
Shouldnt the first one be the display real interface, example:
[+] changing wlan0's MAC from
then
[+] changing mon0's MAC from

**Comment by aanarchyy** [comment]
it was running twice before, shold be fixed
