### ISSUE TITLE
-endless

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#14]
First pass good. Attack all three. then stuck on first target next runs

./wifite -ponly -pto 60 -padto 20 -endless

 [+] select target numbers (1-45) separated by commas, or 'all': 6,29,33

 [+] 3 targets selected.
 [+] Run 1

 [0:00:00] initializing PixieWPS attack on HARBOR0000 (40:70:09:E1:D0:30)
 [0:01:01] Waiting... 
 [!] unable to complete in 60 seconds
 [+] skipping pixiewps on HARBOR0000

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on TP-L000000000 (00000000:A7:7C)
 [+] E-Nonce found  
 [+] PKE hash found  
 [+] Manufacturer:  TP-LINK 
 [+] Model:  1.0 g... 
 [+] PKR hash found  
 [+] Authkey found  
 [+] E-Hash1 found  
 [+] E-Hash2 found  
 [+] Cracking using pixiewps...

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on yetishouse (000000000:86:48)
 [0:01:01] Waiting... 
 [!] unable to complete in 60 seconds
 [+] skipping pixiewps on yetishouse

 [+] Pixiewps attack failed!
 [+] Run 2

 [0:00:00] initializing PixieWPS attack on HARBOR0000 (0000000:D0:30)
 [0:01:01] Waiting... 
 [!] unable to complete in 60 seconds
 [+] skipping pixiewps on HARBOR0000

 [+] Pixiewps attack failed!
 [+] Run 3

 [0:00:00] initializing PixieWPS attack on HARBOR0000 (0000000:D0:30)
 [0:01:01] Waiting... 
 [!] unable to complete in 60 seconds
 [+] skipping pixiewps on HARBOR0000

 [+] Pixiewps attack failed!
 [+] Run 4

 [0:00:00] initializing PixieWPS attack on HARBOR0000 (0000000:D0:30)
 [0:01:01] Waiting... 
 [!] unable to complete in 60 seconds
 [+] skipping pixiewps on HARBOR0000

 [+] Pixiewps attack failed!
 [+] Run 5

 [0:00:00] initializing PixieWPS attack on HARBOR0000 (0000000:D0:30)
 [0:01:01] Waiting... 
 [!] unable to complete in 60 seconds
 [+] skipping pixiewps on HARBOR0000

 [+] Pixiewps attack failed!
 [+] Run 6

 [0:00:00] initializing PixieWPS attack on HARBOR0000 (00000000:D0:30)
^C0:00:04] Waiting... 
 (^C) Pixiewps attack interrupted
 [+] previously cracked access points:
     ******\* (*********_:37:56) : "Key is '**_********_' and PIN is '**_*******_'"
     DG0000000 (00000000000) : "Key is '8888888888' and PIN is '**_****'"

 [+] quitting

**Comment by nuroo** [comment]
Not fixed in r107

**Comment by aanarchyy** [comment]
Oops, forgot to fix that part, should be good now :-D

**Comment by nuroo** [comment]
ok I'll check right now

**Comment by nuroo** [comment]
completed 4 runs, 3 targets > 120s between targets
completed 6 runs, 5 targets > 30s between targets
Loops 2 all targets thru subsequent runs - fixed

Model and Manufacturer became wrong on run 3 (will email)
crtl C - ends loop > doesn't goto next target while  -endless set
crtl C - ends script > doesn't restore original mac, if -endless and -mac used

**Comment by aanarchyy** [comment]
Will work on Ctrl-c resotring origional mac when -endless is specified, but the premise behind the -endless flag is it's meant to be run unmonitored for extended periods. So monitoring Ctrl-c seems pointless, and will make things significantly more diffucult(ie rewriting a large portion of the code to make it all work, including all wpa/wep attacks), not worth it from my standpoint.  -endless is meant to be run as; run it, go to sleep/weekend-out/vacation then check it when your'e back for any successes.

**Comment by nuroo** [comment]
Point taken.
