### ISSUE TITLE
-c <channel>	channel to scan for targets      [auto] >>>> broken

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#21]
r108
./wifite -ponly -pto 45 -paddto 20 -wpsretry 10 -c1
 NUM ESSID                 CH  ENCR  POWER  WPS?  CLIENT

---

```
1  TG1600000             1  WPA2  60db   wps 
2  10Cle00000             1  WPA2  50db   wps 
3  DG1000000              1  WPA2  49db   wps 
4   thec0000000           9  WPA2  49db   wps 
5  Cro000000                7  WPA2  49db   wps 
6  FAR00000                3  WPA2  49db   wps 
7  TG1600000             11  WPA2  48db   wps 
8  TC8717TF1              6  WPA2  47db   wps 
9  FiO0000000             1  WPA2  46db   wps 
```

   10  R000000000            11  WPA2  46db   wps 
   11  DG00000000             1  WPA2  45db   wps

**Comment by aanarchyy** [comment]
I'm not sure why it isnt working for you, it worked just fine for me...
Stays static on selected channel

**Comment by nuroo** [comment]
I checked on version r109. 
for me it doesnt lock on specified channel. 
nor does it acknowledge that you've set a channel lock. 
It should acknowledge that you've given the -c option, when it starts.

**Comment by aanarchyy** [comment]
./wifite-ng -c 11          

  .;'                     `;,    
 .;'  ,;'`;,  `;,   WiFite v2 (r108)
.;'  ,;'  ,;'`;,  `;,`;,  
::   ::   :   ( )   :   ::   ::  automated wireless auditor
':.  ':.  ':. /_\ ,:'  ,:'  ,:'  
 ':.  ':.    /___\    ,:'  ,:'   designed for Linux
  ':.       /_____\      ,:'  
           /       \             

modified by aanarchyy(aanarchyy@gmail.com)
Credits to wiire,DataHead,soxrok2212,nxxxu,nuroo

 [+] channel set to 11

 [+] scanning for wireless devices...
 [+] initializing scan (mon0), updates at 5 sec intervals, CTRL+C when ready.
 [0:00:01] scanning wireless networks. 0 targets and 0 clients found   

 [+] scanning (mon0), updates at 5 sec intervals, CTRL+C when ready.

   NUM ESSID                 CH  ENCR  POWER  WPS?  CLIENT

---

```
1  XX:XX:XX:FB:53:6C)   11  WPA   99db    no   client
2  IDEXXw1               11  WPA2  19db   wps 
3  XXXXXX Guest      11  WPA2  19db    no 
4 XXXCUSTOMERS          11  WPA2  14db    no   client
5  MCXXX                 11  WPA2  11db    no   client
6  <Length 1>            11  WEP   11db    no 
```

 [0:00:15] deauthing hidden access point XX:XX:XX:FB:53:6C)               

Just tried it now, looks locked onto the channel to me, and also seems to be decloaking as well, so im not sure what to tell you here... and i accidently ran that on 108 and it still worked.

**Comment by aanarchyy** [comment]
looks like in that example you gave you didn't put a space in between -c and 1
Please confirm and close.

**Comment by nuroo** [comment]
confirmed "never Broken"

my apologizes. The space is optional in aircrack-ng and reaver.
