### ISSUE TITLE
just says waiting..

### ISSUE THREAD

**Issue by ghost** [aanarchyy/wifite-mod-pixiewps#23]
[0:30:16] Waiting 

On all targets it just says waiting I am I doing something wrong?? I just used

 ./wifite-ng --wps

**Comment by aanarchyy** [comment]
Several things:
1) you may be targeting access points that aren't vulnerable
2) you may have too low signal
3) target ap may have mac filtering

**Comment by ghost** [comment]
I see thanks I did a few other tests I used -ponly  and everything went smoothly but I have another question for some it got the wps pin but when it passed it to reaver it just didn't work and failed any insight on that?

**Comment by nuroo** [comment]
This is how I'm currently using wifite-ng command line Zaxscdvf
./wifite-ng -ponly -pto 50 -paddto 20 -wpst 60 -wpsretry 5

(-ponly)      so wifite only try pixie attack, (brute force pin later)
(-pto 50)     only spend 50 secs trying to get hashes, if router no respond move on
(-paddto)    if router does respond add alittle more time to get all hashs
(-wpst 60)   if pixie find pin. spend at most 60 secs trying to try find passphrase with router, if not i'll          command line more advanced options, (default 660secs, that means pixie fall anyway. router require more time and attention)
(-wpsretry)  try pin 5 times at most......if not try advanced options and move closer.

**Comment by ghost** [comment]
all right thanks for your help.
