### ISSUE TITLE
decloaking hidden access points during initial scan

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#24]
from https://github.com/brianpow/wifite
 [0:00:43] scanning wireless networks. 33 targets and 6 clients found.  
 [!] [0:00:23] deauthing hidden access point (00:00:00:00:02:30) with no client
 [!] [0:00:23] deauthing hidden access point (00:00:00:00:02:30) with no client
 [!] [0:00:23] deauthing hidden access point (00:00:00:00:02:33) with no client
 [!] [0:00:23] successfully decloaked "ks000000" (00:00:00:00:46:91)
 [!] [0:00:23] deauthing hidden access point (00:00:00:00:A8:10) with client (00:00:00:00:95:C5)
 [!] [0:00:23] deauthing hidden access point (00:00:00:00:81:49) with client (00:00:00:00:32:9E)

This awesome, havent ran across any scripts that do this...... pick'd up several routers trying to "hide".
Not saying COPY. Just bringing your attention, get your thoughts

**Comment by aanarchyy** [comment]
Yeah that's part of the regular wifite, so it's in mine also.

Check around line 1159

**Comment by nuroo** [comment]
Oh really, nice. 
I've never seen this version do it? How activate?

**Comment by FractumSeraph** [comment]
When you're scanning, if you've ever seen an AP that only shows up as a MAC address, whenever you try to attack it this process will start.
