### ISSUE TITLE
Not listing or cracking wps anymore since reaver-wps-fork-t6x update

### ISSUE THREAD

**Issue by vapor99** [aanarchyy/wifite-mod-pixiewps#26]
All APs show 'No' when listing even if they are WPS enabled, therefore wifite will not use pixiewps or reaver to crack them.

**Comment by nuroo** [comment]
confirmed, had this issue since update reaver

**Comment by aanarchyy** [comment]
I've been having a lot of problems with the new updates in reaver, for me, i can't even get wash to show any ap's anymore...

**Comment by nuroo** [comment]
least u looking into it. Wash and Reaver outputs the wps status fine outside of wifite-ng. Probably one line changed in wash somewhere

**Comment by vapor99** [comment]
I haven't had any issues with wash or reaver running on its own.  My guess is its just a parsing problem in wifite-ng

**Comment by aanarchyy** [comment]
Fixed
