### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by armprince** [aanarchyy/wifite-mod-pixiewps#30]
[+] scanning for wireless devices...
phy0
 [+] enabling monitor mode on phy0... done
phy0
 [+] enabling monitor mode on phy0... done
phy0
 [+] enabling monitor mode on phy0... done

 endless

any fix ???

**Comment by aanarchyy** [comment]
Are you sure you are using the most up-to-date version of wifite-ng and all helper apps (t6 reaver, pixiewps, etc...)  

That error looks like one I had fixed several releases ago, pertaining to the update to aircrack-ng.
