### ISSUE TITLE
Clock or progress indicator during pixie attack

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#6]
Count down ideal for time used in -pixiet <sec>

But if not just use the same time coding for wps pin attack, counting up till -pixiet <sec>
or 
same coding the timer uses while searching for access points but set to -pixiet <sec>

**Comment by nuroo** [comment]
Put it on to do

**Comment by aanarchyy** [comment]
Yeah, that is on my todo, just forgot to put it up on the list, just gotta figure out how to do it :-/

**Comment by nuroo** [comment]
Im not a coder, didnt know how hard it was.  
U cant just copy timer code used in other parts of script?

**Comment by aanarchyy** [comment]
More or less what i am trying to do, but for some reason stdout.flush() isn't working for me.
I am playing with a version right now, but all it's doing is scrolling down the screen, not flushing.
I am kind of a coder, but i don't really know python very well. Mosty bash and perl.

**Comment by nuroo** [comment]
Found example of count down code in wep attacks. most attacks in -wep section have a 10 min countdown. Just another place to look

**Comment by aanarchyy** [comment]
Well, added a timer/counter, but i'm not satisfied with it, so i am leaving this open until i fix it the way i would like.

**Comment by nuroo** [comment]
tested 2 commands
./wifite -ponly
./wifite -ponly -pixiet 90

both cases timer during pixie attack didnt progress. Stays zero whole time. It does follow the time set by -pixiet, however. 

root@0000:~/wifite-mod-pixiewps-fddd110bb8e7fcdd5dc470b7a9ba53cab1463d8c# ./wifitemod -ponly -pixiet 90
........................
[0:00:00] initializing PixieWPS attack on DI000000 (0000000:1B:35)

 [!] unable to complete in 90 seconds
 [+] skipping pixiewps on DIR0000000

 [+] Pixiewps attack failed!

 [0:00:00] initializing PixieWPS attack on Chunnel (0000000:06:E0)
 [+] E-Nonce found
 [+] PKE hash found
 [+] PKR hash found
 [+] Authkey found
 [+] E-Hash1 found
 [+] E-Hash2 found
 [+] Cracking using pixiewps...

 [+] PIN found:     0000000
 [+] Handing pin to reaver

 [0:00:00] initializing WPS PIN attack on Chunnel (0000000:06:E0)
 [0:00:08] WPS attack, 0/0 success/ttl, 

 [+] PIN found:     00000000
 [+] WPA key found: 0000000

**Comment by aanarchyy** [comment]
Timer should be fixed now, Closing.
