### ISSUE TITLE
-mac option

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#7]
While script was running, in another terminal window I ran macchanger to check mon0.
macchanger mon0:
  Permanent MAC: 00:00:00:00:11:5g (xxxx, Inc.)
  Current      MAC: 00:00:00:00:11:5g (xxxx, Inc.)
****\* meaning true mac address is actually being used while attacking access point ****\* 

As instructed by the script mon0 was not already active b4 running script

This is procedure I use to insure mon0 is truly spoofed or random, ex wlan1
ifconfig wlan1 down
macchanger -r wlan1
   Permanent MAC: 00:00:00:00:11:5g (xxxx, Inc.)
   Current      MAC: 00:11:00:11:00:11 ( example random)
ifconfig wlan1 up

airmon-ng start wlan1

ifconfig mon0 down
macchanger -m 00:11:00:11:00:11 mon0
   Permanent MAC: 00:00:00:00:11:5g (xxxx, Inc.)
   Current      MAC: 00:11:00:11:00:11 (example random)
ifconfig mon0 up

Then still use --mac=00:11:00:11:00:11 in any reaver commands
Then still use -h 00:11:00:11:00:11 in any aireplay-ng commands

both programs will still use the real mac address of attacking wifi card if only macchanger -r on physical interface.

test for yourself or ask on forums.

**Comment by nuroo** [comment]
This one is major flaw. until fixed false sense of anonymity

**Comment by nuroo** [comment]
to test is if random/spoof mac is being used
Run another window while script running:
macchanger mon0
or
run airodump-ng --bssid -c -mon0 
watch the client mac of attacking card, should be spoofed mac

Current implementation of script
-mac option please Fix

**Comment by aanarchyy** [comment]
Should be fixed in most recent release r106, please confirm.

**Comment by nuroo** [comment]
This I want to test this in depth. Will do deeper testing on this option. 

First impressions:
the script does indeed now spoof both physical and virtual mac. (Although spoof mac  is same manufacturer as real)

I want to test the if:
aireplay-ng is using the spoof mac
reaver is using spoof mac

Had a few issues
version r106 didn't have any success getting hashes on any AP's
I need to figure out if it my process, something I was doing wrong
or 
that script doesn't disable network manager
or 
kill conflicting airmon-ng processes.

I will test this weekend
