### ISSUE TITLE
cracked.txt is unreadable is leafpad

### ISSUE THREAD

**Issue by nuroo** [aanarchyy/wifite-mod-pixiewps#9]
when cracked.txt is opened in leafpad its all machine language. its definitely not ascii.

but if read with GVim, I can read it.

**Comment by nuroo** [comment]
./wifite -cracked
Displays cracked access points as output in terminal window. I guess thats ok. 

I would prefer if script output ascii to cracked.txt. That way it can be read with text editor. 
*.txt implies ascii to me.

**Comment by aanarchyy** [comment]
Another part I didn't write. I'll see if I can do something about it. As far as I remember, it is ASCII but uses a %20 as a delimiter.

**Comment by aanarchyy** [comment]
Should be fixed in most recent release r106, please confirm.

**Comment by nuroo** [comment]
Needs a little formatting. but it was readable if leafpad
